### ISSUE TITLE
world download?

### ISSUE THREAD

**Issue by incomplete-tree** [d-002/dikc-8#1]
can we get the world download anywhere? its not lying around here, or in one of the other links of the video...

**Comment by d-002** [comment]
Hi, if you need the world download, I just added it [here](https://github.com/d-002/dikc-8/blob/main/DIKC-8%20(by%20yt.com-%40D_00).zip).
I firstly didn't add the world download because I thought it would be quite a large file (turned out it's not that bad), so I added a `.litematic` instead. You can open the latter with [Litematica](https://www.curseforge.com/minecraft/mc-mods/litematica).

**Comment by d-002** [comment]
Hi, if you need the world download, I just added it [here](https://github.com/d-002/dikc-8/blob/main/DIKC-8%20(by%20yt.com-%40D_00).zip).
I firstly didn't add the world download because I thought it would be quite a large file (turned out it's not that bad), so I added a `.litematic` instead. You can open the latter with [Litematica](https://www.curseforge.com/minecraft/mc-mods/litematica).

**Comment by incomplete-tree** [comment]
how do i load the assembled code into the computer in minecraft?

**Comment by d-002** [comment]
For this too, you will need Litematica. The compiler should have created a `.litematic` that is placed in `%appdata%/.minecraft/schematics`. In-game, use the Litematica menus to choose and import the created scheme tic and place it like in the YouTube video.
